# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          pow270
paginate:       5
baseurl:        ""
url:            "https://pow270.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         pow270 Team
  url:          http://pow270.github.io
  email:        ping@pow270.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
